# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PLUGIN_NAME: BasicAdmin

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Prepare env
        shell: bash
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish --no-restore

      - name: Clean build directory
        run: |
          mkdir -p addons/counterstrikesharp/plugins/${{env.PLUGIN_NAME}}
          mv BasicAdmin/bin/Debug/net7.0/publish/* addons/counterstrikesharp/plugins/${{env.PLUGIN_NAME}}
          cd addons/counterstrikesharp/plugins/${{env.PLUGIN_NAME}}
          find . -maxdepth 1 ! -name 'BasicAdmin.dll' ! -name 'MySqlConnector.dll' ! -name 'schema.sql' ! -name '.' -type f,d -exec rm -rf {} +

      - uses: actions/upload-artifact@v3
        with:
          name: css-${{env.PLUGIN_NAME}}-${{ env.GITHUB_SHA_SHORT }}
          path: addons
  
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Prepare env
        shell: bash
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: css-${{env.PLUGIN_NAME}}-${{ env.GITHUB_SHA_SHORT }}
          path: addons

      - name: Prepare zip
        run: |
          zip -qq -r css-${{env.PLUGIN_NAME}}-${{ env.GITHUB_SHA_SHORT }}.zip *

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.GITHUB_SHA_SHORT }}
          files: |
            css-${{env.PLUGIN_NAME}}-${{ env.GITHUB_SHA_SHORT }}.zip
          body: |
            ${{ github.event.head_commit.message }}
